### ISSUE TITLE
Quantum Crafter Duplication

### ISSUE THREAD

**Issue by mrmorder** [ftog-thorgal/Unbound#3]
Steps to reproduce: Place down Quantum Crafter and right click it a new one will appear in your inventory. 

You can continue to do this with the new  duplicated crafters.

**Comment by ftog-thorgal** [comment]
I can't replicate this issue. This was a bug but was fixed 26 days ago and Unbound runs the latest version of Quantum Storage (see: https://github.com/gigabit101/QuantumStorage/issues/123)

I will chat with mrmorder in Discord to see if he can replicate it again, and if so then I will visit him on our Unbound public server.

**Comment by ftog-thorgal** [comment]
After visiting mrmorder on our server I was able to replicate it in his base. I was not able to replicate this in my base, the wild, or in single player. Marking this off as a closed because I can't report this without being able to replicate it because the mod author wouldn't know what to look for to fix this.
